#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

INSTANCE_NAME=${INSTANCE_NAME:-k3smulti}

INSTANCE=$(limactl list | grep $INSTANCE_NAME | awk '{print $1}')
if [ -z "$INSTANCE" ]; then
    echo "$INSTANCE not simply stopped"
    exit
fi
limactl stop -f $INSTANCE_NAME
limactl start $INSTANCE_NAME
INSTANCE_NAME=$INSTANCE_NAME ./startRegistry
